id: 509340ba27fe4be0b342cd3ff70e0b73
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_85-The_Question_of_Maitreya-v1
  language: en
  author: ''
  volume: {}
